export const PRODUCTS = 'PRODUCTS';
export const PAGINATE_PRODUCTS = 'PAGINATE_PRODUCTS';
export const MULTIPLE_FILTER = 'MULTIPLE_FILTER';
export const SORTING = 'SORTING';
export const REARRANGING = 'REARRANGING';
export const PRICE_RAGE = 'PRICE_RAGE';